Poetry 2
epcpower/pm pull request #30
Opened 2022-03-01 22:46 UTC by epcAnker

2022-03-07 23:52 UTC, gordon-epc requested changes
Remove MANIFEST.in

2022-03-08 01:02 UTC, gordon-epc approved these changes

2022-03-08 21:44 UTC, bholewin-epc approved these changes

2022-03-16 00:00 UTC, gordon-epc requested changes

2022-03-23 22:26 UTC, gordon-epc commented on .github/workflows/ci.yml
> +          poetry config repositories.epc-power https://epc-power-us-890711758583.d.codeartifact.us-east-2.amazonaws.com/pypi/epc-power/
```suggestion
          poetry config repositories.epc-power https://epc-power-us-${{ secrets.AWS_ACCOUNT_ID }}.d.codeartifact.us-east-2.amazonaws.com/pypi/epc-power/
```

2022-03-23 22:26 UTC, gordon-epc commented on .github/workflows/ci.yml
> +          export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain epc-power-us --domain-owner 890711758583 --query authorizationToken --output text`
```suggestion
          export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain epc-power-us --domain-owner ${{ secrets.AWS_ACCOUNT_ID }} --query authorizationToken --output text`
```

2022-04-13 21:49 UTC, gordon-epc requested changes
Delete the file `DELETEtox.zip`

2022-04-15 21:40 UTC, gordon-epc approved these changes

2022-04-25 21:40 UTC, merged